### ISSUE TITLE
Field and drop-down delete

### ISSUE THREAD

**Issue by Kachev** [Kachev/Capston-Project#6]
## Value Proposition

As a User 
I want to able to delete unnecessary fields from the fields from the Materials and Machines form. 
to edit it if necessary.
​

## Description

​
![Bildschirm­foto 2023-04-11 um 09 19 43](https://user-images.githubusercontent.com/93873677/231088203-abbdcd75-f3a9-47ae-8cb9-b7977c42b83c.png)

## Acceptance Criteria

- [x] Buttons to delete unnecessary drop-down menu and input fields
      ​

## Tasks

- [x] new Branch
- [x] create element/button to delete

**Comment by rabe200** [comment]
lgtm
