### ISSUE TITLE
Toggle function

### ISSUE THREAD

**Issue by Kachev** [Kachev/Capston-Project#8]
## Value Proposition

As a User
I would like to use the arrow to toggle the work report between large and small 
​

## Description

​

![Image](https://user-images.githubusercontent.com/93873677/231409745-b157e2ec-3e2c-4ede-990f-71b9286821a7.png)

## Acceptance Criteria

- [ ] Toggle function to hide information on page 2.

## Tasks

- [x] new branch
- [x] add component / button to hide information
- [x] write test

**Comment by liebeckm** [comment]
Hey Hristo, quite minimalistic but understandable! :) I suggest to add testing for the button to your task list 👍 otherwise looks fine!

**Comment by Kachev** [comment]
Thanks! That's right.. I would still do it😅

**Comment by PReichetanz** [comment]
Hi Hristo, nice work!
Just one minor thing: please add the purpose of this story to the value proposition: "so that..."
